import 'package:flutter/material.dart' show BuildContext;
import 'size_helper_source.dart';

extension SizeHelperBuildContext on BuildContext {
  T sizeHelper<T>({
    bool printScreenInfo = false,
    T? mobileSmall,
    T? mobileSmallLandscape,
    T? mobileNormal,
    T? mobileNormalLandscape,
    T? mobileLarge,
    T? mobileLargeLandscape,
    T? mobileExtraLarge,
    T? mobileExtraLargeLandscape,
    T? tabletSmall,
    T? tabletSmallLandscape,
    T? tabletNormal,
    T? tabletNormalLandscape,
    T? tabletLarge,
    T? tabletLargeLandscape,
    T? tabletExtraLarge,
    T? tabletExtraLargeLandscape,
    T? desktopSmall,
    T? desktopSmallLandscape,
    T? desktopNormal,
    T? desktopNormalLandscape,
    T? desktopLarge,
    T? desktopLargeLandscape,
    T? desktopExtraLarge,
    T? desktopExtraLargeLandscape,
  }) =>
      SizeHelper.of(this, printScreenInfo: printScreenInfo).help<T>(
        mobileSmall: mobileSmall,
        mobileSmallLandscape: mobileSmallLandscape,
        mobileNormal: mobileNormal,
        mobileNormalLandscape: mobileNormalLandscape,
        mobileLarge: mobileLarge,
        mobileLargeLandscape: mobileLargeLandscape,
        mobileExtraLarge: mobileExtraLarge,
        mobileExtraLargeLandscape: mobileExtraLargeLandscape,
        tabletSmall: tabletSmall,
        tabletSmallLandscape: tabletSmallLandscape,
        tabletNormal: tabletNormal,
        tabletNormalLandscape: tabletNormalLandscape,
        tabletLarge: tabletLarge,
        tabletLargeLandscape: tabletLargeLandscape,
        tabletExtraLarge: tabletExtraLarge,
        tabletExtraLargeLandscape: tabletExtraLargeLandscape,
        desktopSmall: desktopSmall,
        desktopSmallLandscape: desktopSmallLandscape,
        desktopNormal: desktopNormal,
        desktopNormalLandscape: desktopNormalLandscape,
        desktopLarge: desktopLarge,
        desktopLargeLandscape: desktopLargeLandscape,
        desktopExtraLarge: desktopExtraLarge,
        desktopExtraLargeLandscape: desktopExtraLargeLandscape,
      );

  T sizeHelperBuilder<T>({
    bool printScreenInfo = false,
    T Function(double width, double height)? mobileSmall,
    T Function(double width, double height)? mobileSmallLandscape,
    T Function(double width, double height)? mobileNormal,
    T Function(double width, double height)? mobileNormalLandscape,
    T Function(double width, double height)? mobileLarge,
    T Function(double width, double height)? mobileLargeLandscape,
    T Function(double width, double height)? mobileExtraLarge,
    T Function(double width, double height)? mobileExtraLargeLandscape,
    T Function(double width, double height)? tabletSmall,
    T Function(double width, double height)? tabletSmallLandscape,
    T Function(double width, double height)? tabletNormal,
    T Function(double width, double height)? tabletNormalLandscape,
    T Function(double width, double height)? tabletLarge,
    T Function(double width, double height)? tabletLargeLandscape,
    T Function(double width, double height)? tabletExtraLarge,
    T Function(double width, double height)? tabletExtraLargeLandscape,
    T Function(double width, double height)? desktopSmall,
    T Function(double width, double height)? desktopSmallLandscape,
    T Function(double width, double height)? desktopNormal,
    T Function(double width, double height)? desktopNormalLandscape,
    T Function(double width, double height)? desktopLarge,
    T Function(double width, double height)? desktopLargeLandscape,
    T Function(double width, double height)? desktopExtraLarge,
    T Function(double width, double height)? desktopExtraLargeLandscape,
  }) =>
      SizeHelper.of(this, printScreenInfo: printScreenInfo).helpBuilder(
        mobileSmall: mobileSmall,
        mobileSmallLandscape: mobileSmallLandscape,
        mobileNormal: mobileNormal,
        mobileNormalLandscape: mobileNormalLandscape,
        mobileLarge: mobileLarge,
        mobileLargeLandscape: mobileLargeLandscape,
        mobileExtraLarge: mobileExtraLarge,
        mobileExtraLargeLandscape: mobileExtraLargeLandscape,
        tabletSmall: tabletSmall,
        tabletSmallLandscape: tabletSmallLandscape,
        tabletNormal: tabletNormal,
        tabletNormalLandscape: tabletNormalLandscape,
        tabletLarge: tabletLarge,
        tabletLargeLandscape: tabletLargeLandscape,
        tabletExtraLarge: tabletExtraLarge,
        tabletExtraLargeLandscape: tabletExtraLargeLandscape,
        desktopSmall: desktopSmall,
        desktopSmallLandscape: desktopSmallLandscape,
        desktopNormal: desktopNormal,
        desktopNormalLandscape: desktopNormalLandscape,
        desktopLarge: desktopLarge,
        desktopLargeLandscape: desktopLargeLandscape,
        desktopExtraLarge: desktopExtraLarge,
        desktopExtraLargeLandscape: desktopExtraLargeLandscape,
      );
}
